ANSSI R38 added
Autom-A/AutomA-Playbooks pull request #18
Opened 2023-11-15 19:20 UTC by 0nid1

2023-11-16 11:46 UTC, Mijux requested changes
Verify that the sudo package is installed else install it

2023-11-20 20:26 UTC, 0nid1 commented
As asked, I added a check to see if sudo is installed. If not and if the remote host has an internet connection, it will install it.

2023-11-20 21:34 UTC, Mijux approved these changes
perfect

2023-12-04 20:19 UTC, aiglematth approved these changes

2023-12-04 20:19 UTC, merged